### ISSUE TITLE
Precompiled binaries for Ubuntu 14.04 may not mine properly

### ISSUE THREAD

**Issue by jbisterfeldt** [jbisterfeldt/GiggleNote#1]
My 14.04 test bed refuses to mine with "ERROR [Miner] Error occured during mining: Enable multithreading to use std::thread: Operation not permitted" and stops mining immediately. I don't expect a lot of 14.04 users (read: any), so I'm not going to investigate this further. 

Comment and let me know if you are impacted by this and need a 14.04 binary.

**Comment by jared201** [comment]
yes happened to me, but I need to know where the code fix was done so I can replicate in my fork. Thanks!

**Comment by jbisterfeldt** [comment]
Thanks for confirming! Try running the make commands from the [readme](https://github.com/jbisterfeldt/GiggleNote/blob/master/README.md) - open up a new issue if you run into trouble, but respond back here if you have the same issue. Be sure to run the binaries built on your machine, they'll be on the /GiggleNote/build/release/ path NOT in /binaries.

**Comment by jared201** [comment]
got this problem while trying to install boost

The following packages have unmet dependencies:
 libboost-all-dev : Depends: libboost-dev but it is not going to be installed
                    Depends: libboost-tools-dev
                    Depends: libboost-atomic-dev but it is not going to be installed
                    Depends: libboost-chrono-dev but it is not going to be installed
                    Depends: libboost-context-dev but it is not going to be installed
                    Depends: libboost-coroutine-dev but it is not going to be installed
                    Depends: libboost-date-time-dev but it is not going to be installed
                    Depends: libboost-exception-dev but it is not going to be installed
                    Depends: libboost-filesystem-dev but it is not going to be installed
                    Depends: libboost-graph-dev but it is not going to be installed
                    Depends: libboost-graph-parallel-dev but it is not going to be installed
                    Depends: libboost-iostreams-dev but it is not going to be installed
                    Depends: libboost-locale-dev but it is not going to be installed
                    Depends: libboost-log-dev but it is not going to be installed
                    Depends: libboost-math-dev but it is not going to be installed
                    Depends: libboost-mpi-dev but it is not going to be installed
                    Depends: libboost-mpi-python-dev but it is not going to be installed
                    Depends: libboost-program-options-dev but it is not going to be installed
                    Depends: libboost-python-dev but it is not going to be installed
                    Depends: libboost-random-dev but it is not going to be installed
                    Depends: libboost-regex-dev but it is not going to be installed
                    Depends: libboost-serialization-dev but it is not going to be installed
                    Depends: libboost-signals-dev but it is not going to be installed
                    Depends: libboost-system-dev but it is not going to be installed
                    Depends: libboost-test-dev but it is not going to be installed
                    Depends: libboost-thread-dev but it is not going to be installed
                    Depends: libboost-timer-dev but it is not going to be installed
                    Depends: libboost-wave-dev but it is not going to be installed

**Comment by jbisterfeldt** [comment]
Checked my 14.04 VM, what happens if you re-run `make` after `sudo apt install libboost1.55-dev`?

**Comment by jared201** [comment]
that's the Boost version I have already, just rerun make j #, 60% so far so good

**Comment by jbisterfeldt** [comment]
I'm willing to pay a bounty for your help in confirming and resolving this issue. Please post an address, and see https://keybase.io/jasonbisterfeldt if you wish to post privately.

**Comment by jared201** [comment]
still got the same issue while running but the other node was able to mine, i just have to wait for the unlock period to see the results

**Comment by jbisterfeldt** [comment]
the other node? OS details? If you're able to confirm, I'll nuke the 14.04 binaries and change the guide to exclude 14.04.

**Comment by jbisterfeldt** [comment]
Also, please confirm whether your other node used prebuilt binaries, or compiled locally. Architecture would be helpful (AMD/Intel 64?)

**Comment by jbisterfeldt** [comment]
I am able to mine with recompiled GiggleWallet binary on 14.04 with the above instruction. 2 users confirm existing binaries are unable to mine, so I'll leave the `confirmed` label on until another user is able to confirm new binaries are able to mine on 14.04.

**Comment by jbisterfeldt** [comment]
Please test updated [14.04 binaries](https://github.com/jbisterfeldt/GiggleNote/tree/master/binaries/Ubuntu%2014.04/Intel64).

**Comment by jbisterfeldt** [comment]
believed fixed, awaiting confirmation - I'm able to mine with the new binaries on Intel 64 Ubuntu 14.04. Will close if another user is able to confirm. Bounty pending for @jared201

**Comment by jared201** [comment]
yes, I can mine now, amount will be unlocked after 10 blocks

[wallet axPqUq]: start_mining 4
Mining started in daemon
[wallet axPqUq]: balance
available balance: 0.00000000, locked amount: 0.00000000
[wallet axPqUq]: Height 12989, transaction 5c61df624f86512b2a929e0e5c9574c1f923f598404cbad889150cec1cd82db9, received 669670.02129342

[wallet axPqUq]: 2989
[wallet axPqUq]: balance
available balance: 0.00000000, locked amount: 669670.02129342
[wallet axPqUq]: Height 12990, transaction b0f3d0bf01af9075617309368e7dc458660e797c07e12659055d0600bcae6dae, received 669667.46670502
Height 12991, transaction 715fff78bdd6170a6b280e830d45620bd6e962be3dd4b124d89ea126f201f106, received 669664.91212637

**Comment by jbisterfeldt** [comment]
Thank you for confirming. Closing this issue. Please share your GiggleNote address for bounty payment.
